-- DROP TABLE WMSG_BODY;
-- DROP TABLE WMSG_ATTACH;
-- DROP INDEX IDX_WMSG_SPROP_VK ON WMSG_SPROP;
-- DROP INDEX IDX_WMSG_NPROP_VK ON WMSG_NPROP;
-- DROP TABLE WMSG_SPROP;
-- DROP TABLE WMSG_NPROP;

CREATE TABLE WMSG_BODY
(
  [GDID]           BINARY(12) NOT NULL,
  [MID]            BINARY(16) NOT NULL,
  [CDT_UTC]        DATETIME   NOT NULL,

  [ADR_FROM]       NVARCHAR(MAX) NULL,
  [ADR_REPLYTO]    NVARCHAR(MAX) NULL,
  [ADR_TO]         NVARCHAR(MAX) NULL,
  [ADR_CC]         NVARCHAR(MAX) NULL,
  [ADR_BCC]        NVARCHAR(MAX) NULL,

  [SUBJECT]        NVARCHAR(2048) NULL,
  [SHORT_BODY]     NVARCHAR(MAX)  NULL,
  [BODY]           NVARCHAR(MAX)  NULL,
  [RICH_BODY]      NVARCHAR(MAX)  NULL,
  [RICH_BODY_CTP]  VARCHAR(1024)  NULL,
  CONSTRAINT PK_WMSG_BODY PRIMARY KEY CLUSTERED ([GDID] ASC)
)
GO

CREATE INDEX IDX_WMSG_BODY_MID ON WMSG_BODY([MID]);
GO

CREATE INDEX IDX_WMSG_BODY_CDT ON WMSG_BODY([CDT_UTC]);
GO


CREATE TABLE WMSG_ATTACH
(
  [GDID]         BINARY(12)  NOT NULL,
  [SEQ]          SMALLINT    NOT NULL,
  [NAME]         NVARCHAR(1024)  NULL,
  [WEIGHT]       INT         NOT NULL,-- in kbytes
  [CONTENT]      VARBINARY(MAX)  NULL,
  [CONTENT_TYPE] VARCHAR(1024)   NULL,
  [CONTENT_URL]  NVARCHAR(2048)  NULL,
  CONSTRAINT PK_WMSG_ATTACH PRIMARY KEY CLUSTERED ([GDID], [SEQ] ASC)
)
GO


CREATE TABLE WMSG_SPROP
(
  [GDID]   BINARY(12)    NOT NULL,
  [KEY]    BIGINT        NOT NULL,
  [SEQ]    SMALLINT      NOT NULL,
  [VAL]    NVARCHAR(256) NULL,     --  someone@something.com
  CONSTRAINT PK_WMSG_SPROP PRIMARY KEY CLUSTERED ([GDID], [KEY], [SEQ])
)
GO

CREATE INDEX IDX_WMSG_SPROP_VK ON WMSG_SPROP([VAL], [KEY]) INCLUDE ([GDID], [SEQ]);
GO


CREATE TABLE WMSG_NPROP
(
  [GDID]   BINARY(12) NOT NULL,
  [KEY]    BIGINT     NOT NULL,
  [SEQ]    SMALLINT   NOT NULL,
  [VAL]    BIGINT     NULL,
  CONSTRAINT PK_WMSG_NPROP PRIMARY KEY CLUSTERED ([GDID], [KEY], [SEQ])
)
GO

CREATE INDEX IDX_WMSG_NPROP_VK ON WMSG_NPROP([VAL], [KEY]) INCLUDE ([GDID], [SEQ]);
GO


