name: QA Test
description: Creates a QA functional test issue
title: "Test:Functional QA Test for issue #..."
labels: ["Testing"]
assignees: 'g8behrens-jungfer, g8Mitchell'
body:
- type: dropdown
  id: environment
  attributes:
    label: Available environments ready for testing
    multiple: true
    options:
      - DEV
      - TEST
      - PROD
