name: Folio QA Test
description: Creates a new Folio QA functional test issue
title: "Test: Functional QA Test for issue(s) #..."
labels: ["Testing"]
assignees: 'g8behrens-jungfer, g8Mitchell'
body:
- type: input
  id: issue
  attributes:
    label: 'GitHub Dev Issue #`s'
    description: Enter the GitHub issue prefixed with '#'
    placeholder: '#NNN, #NNN, #NNN'
  validations:
    required: true
- type: markdown
  id: trr
  attributes:
    value: |
      ## DEV Test Readiness Review (TRR)
      **The engineering team has provided** the following items needed for QA testing:
- type: dropdown
  id: environment
  attributes:
    label: Available environments ready for testing
    multiple: true
    options:
      - DEV
      - TEST
      - PROD
  validations:
    required: true
- type: checkboxes
  id: cases
  attributes:
    label: Test data, cases, notes, scripts available to test?
    description: You may select more than one.
    options:
      - label: Data
      - label: Cases
      - label: Notes
      - label: Scripts
- type: textarea
  id: case-notes
  attributes:
    label: Testing notes
    description: Test case, data, notes, scripts
    placeholder: Add detailed test notes here!
- type: markdown
  id: functional-req
  attributes:
    value: |
      ## Functional Requirements
      **The engineering team has provided** the following items needed for QA testing:
- type: textarea
  id: functionality-desc
  attributes:
    label: Functionality to test
    description: A brief description of the functionality to test
  validations:
    required: true
- type: textarea
  id: preconditions
  attributes:
    label: Preconditions
    description: The preconditions required to test
  validations:
    required: false
- type: textarea
  id: steps
  attributes:
    label: Test Steps
    description: Required steps to test
  validations:
    required: false
- type: textarea
  id: expected-results
  attributes:
    label: Expected Results
    description: A description of the expected results
  validations:
    required: false
- type: checkboxes
  id: qa-criteria-met
  attributes:
    label: '========= QA Exit Criteria Certifications Met ========='
    description: 'The QA team certifies the following results testing:'
    options:
      - label: Achieves the specified expected result
      - label: Meets generally acceptable quality standards
      - label: The testing results are free of critical defects
      - label: Will meet stakeholder expectations
      - label: Test case and requirements documentation provided are accurate and complete
- type: textarea
  id: exit-notes
  attributes:
    label: '========= QA Exit Notes ========='
    description: Notes to be filled out by QA
    placeholder: Notes to be filled out by QA
    value: '** QA TODO **'
  validations:
    required: false
