
GET https://localhost:5001/WeatherForecast/3 HTTP/1.2
Authorization: Basic stanleyjobson:swordfish
Accept: application/json
Content-Type: application/json

###

GET https://localhost:5001/weatherforecast HTTP/1.2
# Authorization: Basic stanleyjobson:swordfish
Accept: application/json
Content-Type: application/json


###

GET https://localhost:5001/sys/backgroundservices HTTP/1.2
# Authorization: Basic stanleyjobson:swordfish
Authorization: Basic c3RhbmxleWpvYnNvbjpzd29yZGZpc2g=
Accept: application/json
Content-Type: application/json

###

curl --request GET --url https://localhost:5001/sys/backgroundservices --header 'accept: application/json' --header 'content-type: application/json' --header 'Authorization: Basic c3RhbmxleWpvYnNvbjpzd29yZGZpc2g='

###

GET https://localhost:5001/sys/backgroundservices/enable HTTP/1.2
Authorization: Basic stanleyjobson:swordfish
Accept: application/json
Content-Type: application/json

###

GET https://localhost:5001/sys/backgroundservices/disable HTTP/1.2
Authorization: Basic stanleyjobson:swordfish
Accept: application/json
Content-Type: application/json




### disable

POST https://localhost:5001/sys/backgroundservices/ HTTP/1.2
Authorization: Basic c3RhbmxleWpvYnNvbjpzd29yZGZpc2g=
Accept: application/json
Content-Type: application/json

{
  "requestType":"Disable"
}


### enable

POST https://localhost:5001/sys/backgroundservices/ HTTP/1.2
Authorization: Basic stanleyjobson:swordfish
Accept: application/json
Content-Type: application/json

{
  "requestType":"Enable"
}


### status

POST https://localhost:5001/sys/backgroundservices/ HTTP/1.2
Authorization: Basic stanleyjobson:swordfish
Accept: application/json
Content-Type: application/json

{
  "requestType":"Status"
}



###

POST https://localhost:5001/token HTTP/1.2
Authorization: Basic stanleyjobson:swordfish
Accept: application/json
Content-Type: application/json

{
  "Email":"jkosh@somewhere.com",
  "Name":"John Kosh",
  "UserIdentity": "jkosh"
}

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSm9obiBLb3NoIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiamtvc2hAc29tZXdoZXJlLmNvbSIsIlVzZXJJZGVudGl0eSI6Imprb3NoIiwiZXhwIjoxNTk5MDExOTMzLCJpc3MiOiJFeGFtcGxlU2VydmVyIiwiYXVkIjoiRXhhbXBsZUNsaWVudHMifQ.HG0icfJ-7sMo_wAQcgzxjHaUktVIl_SlEjlmOAKvrJ0





### status with bearer

POST https://localhost:5001/sys/backgroundservices/ HTTP/1.2
# Authorization: Basic stanleyjobson:swordfish
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSm9obiBLb3NoIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiamtvc2hAc29tZXdoZXJlLmNvbSIsIlVzZXJJZGVudGl0eSI6Imprb3NoIiwiZXhwIjoxNjA2MDA5Nzg2LCJpc3MiOiJFeGFtcGxlU2VydmVyIiwiYXVkIjoiRXhhbXBsZUNsaWVudHMifQ.OGi6764g35Qs1qkD_JyPP-U5av4AHy9ScqXfHQZUxUc
Accept: application/json
Content-Type: application/json

{
  "requestType":"Status"
}



### status with bearer

POST https://localhost:5001/sys/backgroundservices/ HTTP/1.2
# Authorization: Basic stanleyjobson:swordfish
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSm9obiBLb3NoIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiamtvc2hAc29tZXdoZXJlLmNvbSIsIlVzZXJJZGVudGl0eSI6Imprb3NoIiwiZXhwIjoxNjA2MDA5Nzg2LCJpc3MiOiJFeGFtcGxlU2VydmVyIiwiYXVkIjoiRXhhbXBsZUNsaWVudHMifQ.OGi6764g35Qs1qkD_JyPP-U5av4AHy9ScqXfHQZUxUc
Accept: application/json
Content-Type: application/json

{
  "requestType":"Disable"
}
